# ============================== Filebeat inputs ===============================

filebeat.inputs:

  - type: log

    id: ${ES_FILEBEAT_INPUT}
    enabled: true
    paths:
      - /var/log/*.log

    # enable this if your logs are json formatted
    json.keys_under_root: true
    json.add_error_key: false
    json.message_key: log


# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  reload.period: 10s

# =================================== Kibana ===================================

setup.kibana:

host: "dashboard:5601"

# Optional protocol and basic auth credentials.
protocol: "https"
username: "admin"
password: "admin"
ssl.enabled: true

# ---------------------------- Elasticsearch Output ----------------------------
#${ES_FILEBEAT_INDEX_NAME}
setup.ilm.enabled: false

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["opensearch:9200"]

  # Protocol - either `http` (default) or `https`.
  protocol: "http"

  # Authentication credentials - either API key or username/password.
  #username: "admin"
  #password: "admin"

  # Use SSL settings for HTTPS.
  #ssl.enabled: false
  #ssl.verification_mode: none

  allow_older_versions: false

  # Optional data stream or index name. The default is "filebeat-%{[agent.version]}".
  # In case you modify this pattern you must update setup.template.name and setup.template.pattern accordingly.
  index: "${ES_FILEBEAT_INDEX_NAME}"

# ======================= Elasticsearch template setting =======================
setup.template.name: ${ES_FILEBEAT_INDEX_NAME}
setup.template.pattern: "${ES_FILEBEAT_INDEX_NAME}"

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~